[JA] translations
tensorflow/docs-l10n pull request #732
Opened 2023-12-16 12:29 UTC by ilyaspiridonov

Translated by Alconost

2024-01-11 19:38 UTC, ilyaspiridonov commented
@pcoet

2024-01-13 20:48 UTC, pcoet requested changes
@ilyaspiridonov Can you do another QA pass of this? I found some issues. Thanks!

2024-01-13 20:48 UTC, pcoet commented on site/ja/community/contribute/docs_ref.md
> +Note: TensorFlow DocTest uses TensorFlow 2 and Python 3.
It looks like most of this doc is untranslated.

2024-01-13 20:48 UTC, pcoet commented on site/ja/datasets/overview.ipynb
> +        "It handles downloading and preparing the data deterministically and constructing a `tf.data.Dataset` (or `np.array`).\n",
It seems like this was localized and is now back to English(?).

2024-01-13 20:48 UTC, pcoet commented on site/ja/probability/examples/Gaussian_Process_Latent_Variable_Model.ipynb
> +        "GP を使用する 1 つの方法として、回帰が挙げられます。入力 ${x_i}{em0}{i=1}^N$（インデックスセットの要素）と観測値 ${y_i}{/em0}{i=1}^N$ の形式の一連の観測データが与えられた場合、これらを使用して、新しいポイントセット ${x_j^*}_{j=1}^M$ で事後予測分布を形成できます。分布はすべてガウスであるため、これは簡単な線形代数
"cubeic" is not a word in English. I assume this is supposed to be "cubic." What happened here? It seems like the word is spelled correctly in the original: https://www.tensorflow.org/probability/examples/Gaussian_Process_Latent_Variable_Model

2024-04-18 15:54 UTC, joefernandez approved these changes

2024-04-18 15:54 UTC, merged